//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanesaMoraga_EVA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string id_producto { get; set; }
        public string nombre { get; set; }
        public string descripción { get; set; }
        public int precio { get; set; }
        public Nullable<int> stock { get; set; }
        public int id_categoria { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
